from pydantic import BaseModel, Field
from typing import List, Optional
import re


class ChatRequest(BaseModel):
    """
    Request model for standard chat interactions
    """
    message: str = Field(..., min_length=1, max_length=5000, description="User message to process")
    thread_id: Optional[str] = Field(None, min_length=1, max_length=100, description="Optional thread identifier for conversation context")

    def __init__(self, **data):
        super().__init__(**data)
        # Additional validation for thread_id format if provided
        if self.thread_id and not re.match(r'^[a-zA-Z0-9_-]+$', self.thread_id):
            raise ValueError("thread_id must contain only alphanumeric characters, hyphens, and underscores")


class SelectedTextChatRequest(BaseModel):
    """
    Request model for queries based on selected text
    """
    message: str = Field(..., min_length=1, max_length=5000, description="User question about the selected text")
    selected_text: str = Field(..., min_length=1, max_length=10000, description="Text provided by user for context")
    thread_id: Optional[str] = Field(None, min_length=1, max_length=100, description="Optional thread identifier for conversation context")

    def __init__(self, **data):
        super().__init__(**data)
        # Additional validation for thread_id format if provided
        if self.thread_id and not re.match(r'^[a-zA-Z0-9_-]+$', self.thread_id):
            raise ValueError("thread_id must contain only alphanumeric characters, hyphens, and underscores")


class ChatResponse(BaseModel):
    """
    Response model for chat interactions
    """
    answer: str = Field(..., min_length=1, description="Answer generated by the chatbot")
    thread_id: Optional[str] = Field(None, min_length=1, max_length=100, description="Thread identifier for conversation context")
    sources: Optional[List[dict]] = Field([], description="List of sources used in the response")


class HealthResponse(BaseModel):
    """
    Response model for health check endpoint
    """
    status: str = Field(..., pattern=r'^(healthy|unhealthy|degraded)$', description="Overall service health status")
    message: str = Field(..., min_length=1, description="Detailed health message")